ecome/core/urls.py
from django.urls import path
from .views import *
app_name="core"
urlpatterns = [
    path("",HomeView.as_view(),name="homepage"),
    path("products/<slug>/",ItemDetailsView.as_view(),name="item"),
    path("category/<int:slug>/",CategoryView,name="category"),
    path("order-summary/",OrderSummary.as_view(),name="order-summary"),
    path("add-to-cart/<slug>/",AddToCart.as_view(),name="add-to-cart"),
    path("remove-from-cart/<slug>/",RemoveFromCart.as_view(),name="remove-from-cart"),
    path("delete-from-cart/<slug>/",MinusItemCart.as_view(),name="delete-from-cart"),
    path("add-coupon/",AddCoupon.as_view(),name="add-coupon"),
    path("remove-coupon/",RemoveCoupon.as_view(),name="remove-coupon"),
    path("checkout/",CheckoutView.as_view(),name="checkout"),
    path("checkout/paymenthandler/", paymenthandler, name="paymenthandler"),
    path("myorder/",myOrder,name="myorder"),
    path("save-address-action/",save_Address_Action,name="save_Address_Action"),
    
]

ecome/ecome/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("accounts/",include("allauth.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecome/core/models.py
from tabnanny import verbose
from django.conf import settings
from email.mime import image
from pyexpat import model
from tkinter.tix import Balloon
from django.urls import reverse
from pydoc import describe
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    slug=models.SlugField()

    def get_absolute_url(self):
        return reverse("core:category",kwargs={
            'slug':self.slug
        })

    def __str__(self):
        return self.title
########################################   
class Brand(models.Model):
    brand_name=models.CharField(max_length=200)
    slug=models.SlugField()

    def get_absolute_url(self):
        return reverse("core:brand",kwargs={
            'slug':self.slug
        })

    def __str__(self):
        return self.brand_name
##############################################
LABEL_CHOICE=(
    ('P',"primary"),
    ('s',"secondry"),
    ('d',"danger"),
)
class Item(models.Model):
    title=models.CharField(max_length=200)
    category=models.ForeignKey(Category,on_delete=models.SET_NULL,null=True,blank=True)
    label=models.CharField(choices=LABEL_CHOICE,max_length=1)
    slug=models.SlugField()
    description=models.TextField()
    image=models.ImageField()
    price=models.IntegerField()
    discount_price=models.FloatField(null=True,blank=True)
   

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("core:item",kwargs={
            'slug':self.slug
        })   
#########################

class Variation(models.Model):
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    name=models.CharField(max_length=200)
    
    def __str__(self):
        return self.name

#############################

class ItemVariation(models.Model):
    variation=models.ForeignKey(Variation,on_delete=models.CASCADE)
    value=models.CharField(max_length=200)#L,M,S,XL,RED,
    attachment=models.ImageField(blank=True)
    class Meta:
        unique_together=(
            ('variation','value')
        )

    def __str__(self):
        return self.value

##################

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered=models.BooleanField(default=False)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)          
    qty=models.IntegerField(default=1)
    item_variations=models.ManyToManyField(ItemVariation)
    
    def get_total_price(self):
        return self.qty * self.item.price

    

    def get_total_discount_price(self):
        return self.qty * self.item.discount_price

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        else:
            return self.get_total_price()
    def get_saved_amount(self):
        return self.get_total_price() - self.get_final_price()
    
    def total_discount_percent(self):
        return int(100-(self.item.discount_price/self.item.price)*100)
    
############

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ref_code=models.CharField(max_length=200)
    items=models.ManyToManyField(OrderItem)
    start_date=models.DateTimeField(auto_now_add=True)
    address=models.ForeignKey("Address",related_name="shipping_address",on_delete=models.SET_NULL,blank=True,null=True)
    payment=models.ForeignKey("Payment",on_delete=models.SET_NULL,blank=True,null=True)
    coupon=models.ForeignKey("Coupon",on_delete=models.SET_NULL,blank=True,null=True)
    ordered=models.BooleanField(default=False)
    being_delivered=models.BooleanField(default=False)
    recieved=models.BooleanField(default=False)
    refund_required=models.BooleanField(default=False)
    refund_granted=models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total=0
        for order_item in self.items.all():
            total +=order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total
    def get_total_tax(self): 
        total=self.get_total()
        return round(0.18 * total)
    def get_total_discount_amount(self):
        total=0
        for order_item in self.items.all():
            total += order_item.get_saved_amount()
        return total
    
    def get_payable_amount(self):
        return self.get_total_tax() + self.get_total()
##################
CITY_CHOICE=(
    ("PR","purnea"),
    ("PAT","Patna"),
   
)
STATE_CHOICE=(
    ("br","Bihar"),
    ("dl","Delhi"),
    ("dl","Delhi"),
)
ADDRESS_CHOICE=(
    ("H","HOME"),
    ("O","OFFICE"),
)
class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name=models.CharField(max_length=200)
    contact=models.IntegerField()
    pincode=models.IntegerField()
    locality=models.CharField(max_length=200)
    street_address=models.TextField()
    city=models.CharField(choices=CITY_CHOICE,max_length=20)
    city=models.CharField(choices=STATE_CHOICE,max_length=20)
    landmarks=models.CharField(max_length=200,blank=True,null=True)
    alternative_no=models.IntegerField(blank=True,null=True)
    address_type=models.CharField(choices=ADDRESS_CHOICE,blank=True,null=True,max_length=1)
    default=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural="Addresses"


#########################

class Payment(models.Model):
    text_id=models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    amount=models.IntegerField()
    timestamp=models.DateTimeField(auto_now_add=True)

###########################
class Coupon(models.Model):
    code=models.CharField(max_length=200)
    amount=models.FloatField()
    def __str__(self):
        return self.code
################

class Refund(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    reason=models.TextField()
    accepted=models.BooleanField(default=False)
    email=models.EmailField()

    def __str__(self):
        return f"{self.pk}"

ecome/core/forms.py
from django import forms

from .models import Address
class CouponForm(forms.Form):
    code=forms.CharField(widget=forms.TextInput(attrs={
        'class':"form-control",
        'placeholder':"Promo Code"
    }))

class CheckoutForm(forms.ModelForm):
    class Meta:
        model= Address
        exclude=("user",)

ecome/core/views.py
from multiprocessing import context
import random
import string

from django.conf import settings

from .forms import CouponForm,CheckoutForm
from pyexpat import model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from re import template
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
import razorpay
from django.http import HttpResponseBadRequest
from unicodedata import category
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import ListView,DetailView,View,UpdateView,CreateView
from .models import Address, Coupon, Item, ItemVariation, OrderItem,Order, Payment,Variation,Category
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages 
# Create your views here.
razorpay_client = razorpay.Client(
    auth=(settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET)
)
class HomeView(ListView):
    model=Item
    template_name="index.html"
    
    def get_context_data(self):
        context=super(HomeView,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['count']=OrderItem.objects.filter(ordered=False).count()
        return context
#not working
def CategoryView(request,slug):
    a=Category.objects.get(pk=slug)
    
    context={"object_list":Item.objects.filter(category=a)}
    
    context= {"categories":Category.objects.all()}

    return render(request,"index.html",context)
class ItemDetailsView(DetailView):
    model=Item
  
    template_name="product.html"
    slug_url_kwarg="slug"

    def get_context_data(self,*args,**kwargs):
        context=super(ItemDetailsView,self).get_context_data(*args,**kwargs)
        context['items'] = Item.objects.exclude(slug=self.kwargs['slug'])
        #context['count']=OrderItem.objects.filter(user=self.request.user,ordered=False).count()

        return context

class AddToCart(LoginRequiredMixin,View):
    def get(self,request,slug,*args,**kwargs):
        item=get_object_or_404(Item,slug=slug)
        order_item,created=OrderItem.objects.get_or_create(item=item,user=request.user,ordered=False)
        var=[]
        varient=Variation.objects.filter(item=item)
        for v in varient:
            var.append(request.GET.get(v.name,None))
        order_qs = Order.objects.filter(user=request.user,ordered=False)

        if order_qs.exists():
            order = order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                order_item.qty +=1
                order_item.save()
                messages.success(request,"your quantity is updated sussecfully")
                return redirect("core:order-summary")
                
            else:
                order.items.add(order_item)
                
                for v in var:
                    a=ItemVariation.objects.get(value=v,variation__item__slug=item.slug)
                    
                    order_item.item_variations.add(a)
                    
                return redirect("core:order-summary")
        else:
            ordered_date=timezone.now()
            order=Order.objects.create(user=request.user,start_date=ordered_date)
            order.items.add(order_item)
            messages.success(request,"your order is successfully")
            return redirect("core:order-summary")

class OrderSummary(LoginRequiredMixin,View):
    def get(self,*args,**kwargs):
        try:
            order=Order.objects.get(user=self.request.user,ordered=False)
            if order.items.count()<1:
                return redirect("core:homepage")
            context={"object":order,"couponform":CouponForm()}
            #print(context)
        except ObjectDoesNotExist:
            return redirect("core:homepage")
        
        return render(self.request,"order-summary.html",context)
    
    model=Order
    template_name="order_summary.html"
#class RemoveFromCart(LoginRequiredMixin,View):
    #def get(self,request,slug,*args,**kwargs):
        #item=get_object_or_404(Item,slug=slug)
        #order_item=OrderItem.objects.get(item=item,user=request.user,ordered=False)
        #order_qs=Order.objects.filter(user=request.user,ordered=False,items=order_item)

        #if order_qs.exists():
            #order=order_qs[0]
            #if order.items.filter(item__slug=item.slug):
                #order_item.qty -=1
                #order_item.save()
                #return redirect("core:order-summary")
            #else:
                #return redirect("core:order-summary")
        #else:
            #return redirect("core:order-summary")
class RemoveFromCart(LoginRequiredMixin,View):
    def get(self,request,slug,*args,**kwargs):
        item=get_object_or_404(Item,slug=slug)
        order_qs=Order.objects.filter(user=request.user,ordered=False)
        
        if order_qs.exists():
            order = order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                order_item=OrderItem.objects.filter(item=item,user=request.user,ordered=False)[0]
                order.items.remove(order_item)
                order_item.delete()
                return redirect("core:order-summary")
                
            else:
                return redirect("core:order-summary")
        else:
            return redirect("core:order-summary")
    
#def RemoveItem(request,slug):
    #item=get_object_or_404(Item,slug=slug)
    #order_item=OrderItem.objects.get(item=item,user=request.user,ordered=False)
    #order_qs=Order.objects.filter(user=request.user,ordered=False,items=order_item)
    #if order_qs.exists():
        #order=order_qs[0]
        #if order.items.filter(item__slug=item.slug):
            #order_item.delete()
            
            #return redirect("core:order-summary")
        #else:
            #return redirect("core:order-summary")
    #else:
        #return redirect("core:order-summary")
class MinusItemCart(LoginRequiredMixin,View):
    def get(self,request,slug,*args,**kwargs):
        item=get_object_or_404(Item,slug=slug)
        order_item,created=OrderItem.objects.get_or_create(user=request.user,ordered=False,item=item)
        #for varient
        var=[]
        varient=Variation.objects.filter(item=item)
        for v in varient:
            var.append(request.GET.get(v.name,None))
        order_qs=Order.objects.filter(user=request.user,ordered=False)
        if order_qs.exists():
            order=order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                if order_item.qty > 1:
                    order_item.qty -=1
                    order_item.save()
                else:
                    order_item.delete()
                return redirect("core:order-summary")
        else:
            return redirect("core:order-summary")
def check_coupon(request,code):
    try:
        code=Coupon.objects.get(code=code)
        return True
    except ObjectDoesNotExist:
        return False

def get_coupon(request,code):
    try:
        coupon=Coupon.objects.get(code=code)
        return coupon
    except ObjectDoesNotExist:
        return redirect("core:order-summary")


class AddCoupon(View):
    def post(self,*args,**kwargs):
        if self.request.method == "POST":
            form=CouponForm(self.request.POST or None)
            if form.is_valid():
                try:
                    code=form.cleaned_data.get("code") 
                    if check_coupon(self.request,code):
                        order=Order.objects.get(user=self.request.user,ordered=False)
                        order.coupon = get_coupon(self.request,code)
                        order.save()
                        return redirect("core:order-summary")
                    else:
                        return redirect("core:order-summary")
                except ObjectDoesNotExist:
                    return redirect("core:order-summary")


class RemoveCoupon(View):
    def get(self,*args,**kwargs):
        order=Order.objects.get(user=self.request.user,ordered=False)
        order.coupon = None
        order.save()
        return redirect("core:order-summary")
            
class CheckoutView(View):

    def get(self,*args, **kwargs):
        address=Address.objects.filter(user=self.request.user)
        context={}
        try:
            order=Order.objects.get(user=self.request.user,ordered=False)
            form=CheckoutForm()
            amount = order.get_payable_amount() * 100
            currency = "INR"
            DATA = {
                "amount": amount,
                "currency": currency,
            }
            order_id = razorpay_client.order.create(data=DATA)

            context["order"] = order
            context["form"] = form
            context["address"] = address
            context["razorpay_key"] = settings.RAZOR_KEY_ID
            context["amount"] = order.get_payable_amount()
            context["order_id"] = order_id["id"]
            return render(
                self.request,
                "checkout.html",
                context=context,
            )
           

        except ObjectDoesNotExist:
            return redirect("core:checkout")
    def post(self,*args, **kwargs):
        if self.request.method == "POST":
            order=Order.objects.get(user=self.request.user,ordered=False)
            form=CheckoutForm(self.request.POST or None)
            #save_address=self.request.POST.get("save_address",None)
            
            if form.is_valid():
                data=form.save(commit=False)
                data.user=self.request.user
                data.save()
                order.address=data
                order.save()
                #makePayment(self,request)
                return redirect("core:checkout")
            else:
                return redirect("core:checkout")
        else:

ecome/core/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <h2>CheckOut Form</h2>
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">Select any One adress</div>
                <form action="{% url 'core:save_Address_Action' %}" method="POST">
                    {% csrf_token %}
                    {% for i in address %}
                    <div class="mb-3 ms-3">
                        
                            <input class="btn-check" type="radio" name="save_address" value="{{i.id}}" id="i{{forloop.counter}}" autocomplete="off">
                            <label class="btn btn-outline-secondary w-100" for="i{{forloop.counter}}">
                                <h6>{{i.name}} - {{i.contact}}</h6>
                                <p class="m-0">{{i.locality}} {{i.get_city_display}} {{i.get_state_display}}</p>
                                <p class="m-0">Pincode:{{i.pincode}}</p>
                              
                            </label>
                          
                    </div>
                    {% endfor %}
                    <div class="mb-3">
                        <input type="submit" class="btn btn-success w-100" value="Payment" name="save_address_btn">
                    </div>
                    
                    
                </form>
            </div>
            
        </div>
        <div class="col-lg-6">
            
            <div class="card">
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form|crispy}}
                        <div class="mt-3">
                            <input type="submit" class="btn btn-success w-100" v>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<button id="rzp-button1">Pay</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
  var options = {
    key: "{{razorpay_key}}", // Enter the Key ID generated from the Dashboard
    amount: "{{amount}}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    currency: "INR",
    order_id: "{{order_id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    handler: function (response) {
      alert(response.razorpay_payment_id);
      alert(response.razorpay_order_id);
      alert(response.razorpay_signature);
    },
    prefill: {
      name: "{{request.user.username}}",
      email: "{{request.user.email}}",
      contact: "{{address.0.contact}}",
    },

    theme: {
      color: "#3399cc",
    },
  };
  var rzp1 = new Razorpay(options);
  rzp1.on("payment.failed", function (response) {
    alert(response.error.code);
    alert(response.error.description);
    alert(response.error.source);
    alert(response.error.step);
    alert(response.error.reason);
    alert(response.error.metadata.order_id);
    alert(response.error.metadata.payment_id);
  });
  document.getElementById("rzp-button1").onclick = function (e) {
    rzp1.open();
    e.preventDefault();
  };
</script>
{% endblock  %}

ecome/core/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-lg-3 mb-3 d-sm-block d-none">
           <div class="list-group">
               {% for i in categories %}
                    <a href="" class="list-group-item list-group-item-action">{{i.title}}</a>
               {% endfor %}
              
           </div>
        </div>
        <div class="col-lg-9">
            <div class="row">
              
                {% for item in object_list %}
                        <div class="col-lg-3 mb-3">
                            <div class="card shadow">
                                <img src="{{item.image.url}}" class="card-img-top" alt="" style="height:270px;">
                                <div class="card-body">
                                    <h6>{{ item.get_category_display }}</h6>
                                    <h6>
                                        <a href="{{ item.get_absolute_url }}" class="text-truncate text-capitalize text-decoration-none">{{item.title}}</a>
                                    </h6>
                                  
                                </div>
                            </div>
                        </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

ecome/core/templates/order-summary.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid g-3">
    <div class="row">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{message.tags}}">{{message}}</div>
            {% endfor %}
        {% endif %}
        <div class="col-lg-8">
            {% for order_item in object.items.all %}
            <div class="media  mt-3 d-md-flex shadow p-2 d-block">
                <img src="{{order_item.item.image.url}}" width="120px" class="media-image d-block shadow" alt="">
                <div class="media-body ps-3">
                    <h5 class="mt-5 fw-bolder">{{order_item.item.title}}</h5>
                  <span class="d-block">
                    {% if order_item.item_variations.exists %}
                    {% for foo in order_item.item_variations.all %}
                    <small class="text-muted">{{foo.variation.name}}:{{foo.value}}</small>
                    {% endfor %}
                    {% endif %}
                  </span>
                  <span class="d-block my-2">
                      {% if order_item.item.discount_price %}
                        <p class="text-dark h5 fw-bold d-inline">Rs.{{ order_item.get_total_discount_price }}</p>
                        <p class="text-dark h5 fw-normal d-inline"><del>Rs.{{order_item.get_total_price}}</del></p>
                        <p class="text-success fw-bold">Total Saved Amount: Rs.{{order_item.get_saved_amount}}({{order_item.total_discount_percent}}%)</p>
                      {% else %}
                      <p class="text-dark h5 fw-normal d-inline">Rs.{{order_item.item.price}}</p>
                      {% endif %}
                  </span>
                  <span class="d-inline-block">
                      <a href="{% url 'core:delete-from-cart' order_item.item.slug %}" class="btn btn-danger fw-bolder">-</a>
                      
                      <span class="">{{order_item.qty}}</span>
                      <a href="{% url 'core:add-to-cart' order_item.item.slug %}" class="btn btn-warning fw-bolder">+</a>
                  </span>
                  <div class="d-inline-block mt-2">
                      <a href="{% url 'core:remove-from-cart' order_item.item.slug %}" class="btn btn-secondary ">Remove</a>
                  </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-lg-4">
            <h3 class=" mt-3 display-6">Price BreakPoint</h3>
            <div class=" list-group">
                <div class="list-group-item list-group-item-action">
                    <span class="fw-bold">Total Amount</span>
                    <span class="float-end">₹{{object.get_total}} /-</span>
                </div>
                <div class="list-group-item list-group-item-action">
                    <span class="fw-bold">Tax Gst(18%)</span>
                    <span class="float-end"> +₹{{object.get_total_tax}} /-</span>
                </div>
                {% if object.get_total_discount_amount > 0.0%}
                <div class="list-group-item list-group-item-action bg-success text-white">
                    <span class="fw-bold">Total Discount</span>
                    <span class="float-end">-₹{{object.get_total_discount_amount}} /-</span>
                </div>
                {% endif %}
                {% if object.coupon %}
                <div class="list-group-item list-group-item-action text-success">
                    <span class="fw-bold">Coupon discount</span>
                    <span class="float-end">-₹500 /-<a href="" class="btn btn-info ms-2 btn-sm">X</a></span>
                </div>
               
                {% endif %}
                <div class="list-group-item list-group-item-action display-6">
                    <span class="fw-bold mb-1">Total payable</span>
                    <span class="float-end small">₹{{object.get_payable_amount}} /-</span>
                </div>
                
            </div>
            {% if object.coupon %}
            <h2>This coupon is added <a href="{% url 'core:remove-coupon' %}" class="">Remove</a></h2>
            {% else %}
            <div class="card mt-3">
                <div class="card-body">
                    <form action="{% url 'core:add-coupon' %}" method="post" class="d-flex">
                        {% csrf_token %}
                        {{couponform}}
                        <input type="submit" class="btn btn-danger" value="Go">
                    </form>
                </div>
            </div>
            {% endif %}
            <div class="row mt-2">
                <div class="col">
                    <div class="btn btn-warning w-100">Continue SHoping</div>
                    
                </div>
                <div class="col">
                    <a href="{% url 'core:checkout' %}" class="btn btn-success w-100">Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

ecome/core/templates/product.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">

    <div class="row">
        
       
        <div class="col-lg-10">
            <div class="row">
                
                        <div class="col-lg-3">
                            <img src="{{object.image.url}}" class="card-img-top" alt="" style="height:350px;width:250px">
                        </div>
                        <div class="col-lg-9">
                            <div class="card shadow-lg">
                                
                                <div class="card-body">
                                    <h6>{{object.title}}</h6>
                                    <h6>{{object.category.title}}</h6>
                                    <h6>{{object.discount_price}}     <del>{{object.price}}</del></h6>

                                   
                                    <a href="" class="btn btn-success float-start">Buy now</a>
                                    <form action="{% url 'core:add-to-cart' object.slug %}" class="">
                                        {% for foo in object.variation_set.all %}
                                             <p>{{foo.name}}</p>
                                             {% for val in foo.itemvariation_set.all %}
                                                 <input type="radio" class="form-check-input" value="{{val.value}}" name="{{foo.name}}" required/>
                                                 <label for="" class="form-check-label">{{val.value}}</label>
     
                                             {% endfor %}
                                        {% endfor %}
                                     <input type="submit" value="Add To Cart" class="btn btn-primary ms-2">
                                     </form>
                                  
                                </div>
                            </div>
                        </div>
               
            </div>
        </div>
    </div>
</div>
<div class="container mt-3 d-sm-block d-none">
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                
                {% for item in items %}
                    {% comment %} {% if  object.category.id == item.category.id  %}  {% endcomment %}
                        <div class="col-lg-3">
                            <div class="card shadow-lg">
                                <img src="{{item.image.url}}" class="card-img-top" alt="" style="height:270px;width:302px" >
                                <div class="card-body">
                                    <h6>{{ item.get_category_display }}</h6>
                                    <h6>
                                        <a href="{{ item.get_absolute_url }}" class="text-truncate text-capitalize text-decoration-none">{{item.title}}</a>
                                    </h6>
                                  
                                </div>
                            </div>
                        </div>
                         {% comment %} {% endif %}  {% endcomment %}
                {% endfor %}
                
            </div>
        </div>
    </div>
</div>
{% endblock %}